POST http://localhost:8080/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="videoplayback.mp4"

< C:\Users\SUKHROB\Desktop\videoplayback.mp4

###

POST http://localhost:8080/attach/admUser/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcwOTA1MTAsImV4cCI6MTY1NzMwNjUxMCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo1LCJyb2xlIjoiUk9MRV9BRE1JTiJ9.P9PN81VIGV0YBjgsWBfBqYUS3ZEjXfngt-EYFIAfWaM


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="videoTest.mp4"

< C:\Users\Acer\Downloads\videoTest.mp4



 "tagList": [
    "sotsial",
    "d2as"
  ]

###

GET localhost:8080/attach/admUser/pagination?page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcwOTA1MTAsImV4cCI6MTY1NzMwNjUxMCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo1LCJyb2xlIjoiUk9MRV9BRE1JTiJ9.P9PN81VIGV0YBjgsWBfBqYUS3ZEjXfngt-EYFIAfWaM
###
GET localhost:8080/attach/all/open_general/c0f20d4d-2f49-414e-9648-0fceeb762b3b

###
DELETE http://localhost:8080/attach/admUser/delete/4028dfd181d2670f0181d269f3e20002