POST localhost:8080/video/user/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc2ODcxNDIsImV4cCI6MTY1NzkwMzE0MiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo4LCJyb2xlIjoiUk9MRV9VU0VSIn0.cU5c2eHiG28hvON3D7PFjccZI3-lShjDaquKxFm8aYI

{
  "name": "Konsert",
  "attach": "4028dfd181d26c2a0181d26c7d4d0000",
  "channel": "402866d181f0e8fa0181f0eab1430000",
  "description": "Konsert xajviy",
  "review": "4028dfd181d26c2a0181d26c7d4d0000",
  "key": "konsertcha",
  "title": "xajviy kulgu",
  "category": "MultFilm",
  "type": "SHORT",
  "status": "PUBLIC"
}

###

GET http://localhost:8080/video/user/list
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc2ODcxNDIsImV4cCI6MTY1NzkwMzE0MiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo4LCJyb2xlIjoiUk9MRV9VU0VSIn0.cU5c2eHiG28hvON3D7PFjccZI3-lShjDaquKxFm8aYI

###

GET http://localhost:8080/video/public/byId/402866d181f0e8fa0181f0eab1430000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc2ODcxNDIsImV4cCI6MTY1NzkwMzE0MiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo4LCJyb2xlIjoiUk9MRV9VU0VSIn0.cU5c2eHiG28hvON3D7PFjccZI3-lShjDaquKxFm8aYI


###

PUT http://localhost:8080/video/ownUser/fullUpdate/konsertcha
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc2ODcxNDIsImV4cCI6MTY1NzkwMzE0MiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo4LCJyb2xlIjoiUk9MRV9VU0VSIn0.cU5c2eHiG28hvON3D7PFjccZI3-lShjDaquKxFm8aYI

{
  "name": "Tom and Jerry",
  "attach" : "4028dfd181d26c2a0181d26c7d4d0000",
  "channel" : "402866d181f0e8fa0181f0eab1430000",
  "description": "Tom and Jerry about chesse",
  "review": "4028dfd181d26c2a0181d26c7d4d0000",
  "key" : "TomAndJerry",
  "title": "catch the jeery",
  "category": "MultFilm",
  "type": "VIDEO"
}

###

PUT http://localhost:8080/video/ownUser/changeVideoStatus/TomAndJerry
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc2ODcxNDIsImV4cCI6MTY1NzkwMzE0MiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo4LCJyb2xlIjoiUk9MRV9VU0VSIn0.cU5c2eHiG28hvON3D7PFjccZI3-lShjDaquKxFm8aYI


###

PUT http://localhost:8080/video/public/IncreaseVideoViewCountByKey/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc2ODcxNDIsImV4cCI6MTY1NzkwMzE0MiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo4LCJyb2xlIjoiUk9MRV9VU0VSIn0.cU5c2eHiG28hvON3D7PFjccZI3-lShjDaquKxFm8aYI

{
  "name": "Mp3"
}

###

DELETE http://localhost:8080/video/adm/delete/9
Authorization: Bearer

###

GET localhost:8080/video/public/pagination?categoryId=8&page=0&size=10

###

GET localhost:8080/video/public/search_text?search_text=Tom and jerry&page=0&size=10

###

GET localhost:8080/video/adnOwn/8a8a83fb81f607a50181f6083e3c0000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgwMzQ4MjYsImV4cCI6MTY1ODI1MDgyNiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo1LCJyb2xlIjoiUk9MRV9BRE1JTiJ9.5yh7rq4ozL8yxPhiEcdzFj3oMp0hAhxW692SHC87HBM

###

GET localhost:8080/video/adm/pagination?page=0&size=10

###

GET localhost:8080/video/public/search_channel?channleId=402866d181f0e8fa0181f0eab1430000&page=0&size=10